# Site settings
title: Dewberry Bees
email: stefan@dewberrybees.com
url: https://www.dewberrybees.com
description: "Dewberry Bees is a small beekeeping business in Nailsea, North Somerset, producing local wildflower honey and natural beeswax products. Support the environment with our adopt-a-bee and hive sponsorship packages."
keywords: "Dewberry Bees, Nailsea honey, North Somerset honey, local honey, wildflower honey, beeswax products, adopt a bee, hive sponsorship, beekeeping, eco-friendly gifts, natural skincare, sustainable beekeeping, support pollinators"
skills: "Honey - Beekeeping - Beeswax Products"
meta_author: Dewer Stefan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FFC117 #80B3FF
  primary-rgb: "255,193,23" #"128,179,255"
  secondary: 9F84BD #FD6E8A
  secondary-dark: 644498 #A2122F

# Footer settings
footer:
  copyright: Dewberry Bees
  location: Location
  social: Socials
  #credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/dewberrybees
  - title: facebook
    url: https://www.facebook.com/dewberrybees 

# Postal address (add as many lines as necessary)
address:
  - line: Nailsea
  - line: North Somerset, UK

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
